package.json
pnpm-lock.yaml
src/pages/api/v0/announcements.ts
src/pages/api/v0/settings/flags.ts

Add OCG feature flag for mobile LW and update wallet-core to walletkit-core
Fixes #
Link:
<details>
</details>
<details>
</details>

feature(core): add ocg feature flag and update walletkit-core 

---

src/pages/api/v0/settings/flags.ts

update name and description for cfp/dfip feature flag
Fixes #
Link:
<details>
</details>
<details>
</details>

chore(flags): update cfp/dfip flag name and description

---

package.json
pnpm-lock.yaml

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(deps): update to standard

---

src/pages/api/v0/settings/flags.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(core): update cfp/dfip feature flag to beta

---

src/pages/api/v0/settings/flags.ts

- To allow internal testing on playground 
Fixes #
Link:
<details>
</details>
<details>
</details>

chore(flag): update ocg flag to >2.13.1

---

src/pages/api/v0/settings/flags.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(deps): disable OCG

---

src/pages/api/v0/settings/flags.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(flags): enable CFP creation

---

src/pages/api/v0/settings/flags.ts

Update title to "Governance"
Fixes #
Link:
<details>
</details>
<details>
</details>

chore(api): update ocg beta flag title

---

src/pages/api/v0/announcements.ts

- As titled
- Pending translation
- Not sure which app version we want to allow this too, using latest version for now
- Not sure which `id` is last used, was referring to this https://github.com/DeFiCh/wallet/pull/3756/files

chore(announcement): add announcement to guide user to leverage negative interest rate

---

src/pages/api/v0/announcements.ts

chore(translation): add de and fr to negative interest rate announcement

---

src/pages/api/v0/announcements.ts

chore(api): update announcement for negative rate

---

src/pages/api/v0/announcements.ts

- As titled
- Did not increment `id` because this is same announcement

chore(announcement): update url and zh translations

---

.github/ci-e2e.yml
cypress.config.js
cypress/.eslintrc
cypress/e2e/bridge/limits.spec.ts
cypress/e2e/wallet/announcements.spec.ts
cypress/e2e/wallet/flags.spec.ts
cypress/plugins/index.ts
cypress/support/commands.ts
cypress/support/e2e.ts
cypress/tsconfig.json
package.json
pnpm-lock.yaml

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(e2e): add setup for Cypress to test response

---

cypress/e2e/bridge/status.spec.ts
src/pages/api/v0/bridge/status.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

feature(bridge/status): return status flag

---

src/pages/api/v0/bridge/status.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(api): temporarily put down bridge

---

cypress/e2e/bridge/announcements.spec.ts
src/pages/api/v0/bridge/announcements.ts

As titled. We only added required data as of now (`BridgeAnnouncement` interface), we can add more later if needed.
Partially Fixes https://github.com/BirthdayResearch/quantum/issues/735
Link:
<details>
</details>
<details>
</details>

feature(announcements): create announcement list for bridge

---

src/pages/api/v0/bridge/announcements.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

feat(bridge): announcement - add id prop

---

cypress.config.js
cypress/e2e/wallet/announcements.spec.ts
cypress/e2e/wallet/flags.spec.ts
cypress/fixtures/announcements.json
cypress/fixtures/flags.json

Added verification of responses with hardcoded fixtures for:
```
/api/v0/settings/flags
/api/v0/announcements
```
Fixes #
Link:
<details>
</details>
<details>
</details>

chore(e2e): added response verifications for /flags and /announcements apis;

---

.github/workflows/ci-e2e.yml
cypress/e2e/wallet/announcements.spec.ts
cypress/e2e/wallet/flags.spec.ts
cypress/fixtures/announcements.json
cypress/fixtures/flags.json
package.json
pnpm-lock.yaml
src/pages/api/v0/bridge/limits.ts
src/pages/api/v0/settings/flags.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(core): add evm flag

---

cypress/fixtures/flags.json
src/pages/api/v0/settings/flags.ts

Partially Fixes DFC 343
Link:
<details>
</details>
<details>
</details>

feat(core): update service provider flag details

---

cypress/fixtures/flags.json
src/pages/api/v0/settings/flags.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(core): enable evm on testnet

---

cypress/fixtures/flags.json
package.json
pnpm-lock.yaml
src/pages/api/v0/settings/flags.ts

There's a dependency PR from walletkit: https://github.com/WavesHQ/walletkit/pull/175/
Fixes #
Link:
<details>
</details>
<details>
</details>

feat(core): add flag for allowing dusd loop

---

cypress/fixtures/flags.json
src/pages/api/v0/settings/flags.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(ops): disable dusd loops on testnet

---

cypress/fixtures/flags.json
src/pages/api/v0/settings/flags.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(ops): enable dusd loops

---

src/pages/api/v0/bridge/status.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(ops): temporarily disable quantum due to hardfork

---

cypress/fixtures/flags.json
src/pages/api/v0/settings/flags.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(ops): enable dusd-loops on mainnet

---

src/pages/api/v0/bridge/status.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(ops): enable quantum

---

cypress/fixtures/flags.json
src/pages/api/v0/settings/flags.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(ops): enable evm on mainnet

---

cypress/fixtures/flags.json
package.json
pnpm-lock.yaml
src/pages/api/v0/settings/flags.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

feat(core): add flag for allowing save tx

---

cypress/fixtures/flags.json
src/pages/api/v0/settings/flags.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(dep): remove save_tx tag

---

cypress/fixtures/flags.json
src/pages/api/v0/settings/flags.ts

Fixes #
Link:
<details>
</details>
<details>
</details>

chore(dep): reenable save_tx tag
